# Generated by Django 5.1 on 2024-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='poster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='poster'),
        ),
        migrations.AddField(
            model_name='tag',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster/', verbose_name='poster'),
        ),
    ]
